[build]
    publish = "public"
    command = "echo No build command"
    functions = "functions"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
